=== pseinfo/database/schema/autogen/atomic.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Atomic",
  "definitions": {
    "Atomic": {
      "type": "object",
      "properties": {
        "@metadata": {
          "type": "object",
          "properties": {
            "lastModified": {
              "type": "string"
            },
            "schemaVersion": {
              "type": "string"
            }
          },
          "required": [
            "lastModified",
            "schemaVersion"
          ],
          "additionalProperties": false
        },
        "electron_config": {
          "type": "string"
        },
        "ionization": {
          "type": "object",
          "properties": {
            "unit": {
              "type": "string",
              "const": "eV"
            },
            "values": {
              "type": "array",
              "items": {
                "type": "number"
              }
            }
          },
          "required": [
            "unit",
            "values"
          ],
          "additionalProperties": false
        },
        "mass": {
          "type": "object",
          "properties": {
            "atomic_mass": {
              "type": "object",
              "properties": {
                "unit": {
                  "type": "string",
                  "const": "u"
                },
                "value": {
                  "type": "number"
                }
              },
              "required": [
                "unit",
                "value"
              ],
              "additionalProperties": false
            },
            "standard_atomic_weight": {
              "type": "object",
              "properties": {
                "deviation": {
                  "type": "number"
                },
                "value": {
                  "type": "number"
                }
              },
              "required": [
                "deviation",
                "value"
              ],
              "additionalProperties": false
            }
          },
          "required": [
            "atomic_mass",
            "standard_atomic_weight"
          ],
          "additionalProperties": false
        },
        "radius": {
          "type": "object",
          "properties": {
            "calculated": {
              "type": "object",
              "properties": {
                "unit": {
                  "type": "string",
                  "const": "pm"
                },
                "value": {
                  "type": "number"
                }
              },
              "required": [
                "unit",
                "value"
              ],
              "additionalProperties": false
            },
            "covalent": {
              "type": "object",
              "properties": {
                "deviation": {
                  "type": "number"
                },
                "unit": {
                  "type": "string",
                  "const": "pm"
                },
                "value": {
                  "type": "number"
                }
              },
              "required": [
                "deviation",
                "unit",
                "value"
              ],
              "additionalProperties": false
            },
            "empirical": {
              "type": "object",
              "properties": {
                "unit": {
                  "type": "string",
                  "const": "pm"
                },
                "value": {
                  "type": "number"
                }
              },
              "required": [
                "unit",
                "value"
              ],
              "additionalProperties": false
            },
            "vdw": {
              "type": "object",
              "properties": {
                "unit": {
                  "type": "string",
                  "const": "pm"
                },
                "value": {
                  "type": "number"
                }
              },
              "required": [
                "unit",
                "value"
              ],
              "additionalProperties": false
            }
          },
          "required": [
            "calculated",
            "covalent",
            "empirical",
            "vdw"
          ],
          "additionalProperties": false
        },
        "shell": {
          "type": "array",
          "items": {
            "type": "number"
          }
        }
      },
      "additionalProperties": false
    }
  }
}

=== pseinfo/database/elements/i/atomic.json
{
  "@metadata": {
    "lastModified": "2025-09-30T13:52:31.987Z",
    "schemaVersion": "1"
  },
  "electron_config": "Kr 4d[10] 5s[2] 5p[5]",
  "ionization": {
    "unit": "eV",
    "values": [
      10.45126,
      19.13126,
      29.57,
      40.357,
      51.52,
      74.4,
      87.61
    ]
  },
  "mass": {
    "atomic_mass": {
      "unit": "u",
      "value": 126.904473
    },
    "standard_atomic_weight": {
      "deviation": 0.00003,
      "value": 126.90447
    }
  },
  "radius": {
    "calculated": {
      "unit": "pm",
      "value": 115
    },
    "covalent": {
      "deviation": 3,
      "unit": "pm",
      "value": 139
    },
    "empirical": {
      "unit": "pm",
      "value": 140
    },
    "vdw": {
      "unit": "pm",
      "value": 198
    }
  },
  "shell": [
    2,
    8,
    18,
    18,
    7
  ]
}

=== pseinfo/database/elements/al/atomic.json
{
  "@metadata": {
    "lastModified": "2025-09-30T13:52:31.987Z",
    "schemaVersion": "1"
  },
  "electron_config": "Ne 3s[2] 3p[1]",
  "ionization": {
    "unit": "eV",
    "values": [
      5.985769,
      18.82855,
      28.447642,
      119.9924,
      153.8252
    ]
  },
  "mass": {
    "atomic_mass": {
      "unit": "u",
      "value": 26.98153857
    },
    "standard_atomic_weight": {
      "deviation": 3e-7,
      "value": 26.9815384
    }
  },
  "radius": {
    "calculated": {
      "unit": "pm",
      "value": 118
    },
    "covalent": {
      "deviation": 4,
      "unit": "pm",
      "value": 121
    },
    "empirical": {
      "unit": "pm",
      "value": 143
    },
    "vdw": {
      "unit": "pm",
      "value": 184
    }
  },
  "shell": [
    2,
    8,
    3
  ]
}

=== pseinfo/database/elements/sr/atomic.json
{
  "@metadata": {
    "lastModified": "2025-09-30T13:52:31.987Z",
    "schemaVersion": "1"
  },
  "electron_config": "Kr 5s[2]",
  "ionization": {
    "values": [
      5.6948674,
      11.0302764,
      42.88353,
      56.28,
      70.7
    ],
    "unit": "eV"
  },
  "mass": {
    "atomic_mass": {
      "value": 87.621,
      "unit": "u"
    },
    "standard_atomic_weight": {
      "value": 87.62,
      "deviation": 0.01
    }
  },
  "radius": {
    "empirical": {
      "value": 215,
      "unit": "pm"
    },
    "calculated": {
      "value": 219,
      "unit": "pm"
    },
    "covalent": {
      "value": 195,
      "deviation": 10,
      "unit": "pm"
    },
    "vdw": {
      "value": 249,
      "unit": "pm"
    }
  },
  "shell": [
    2,
    8,
    18,
    8,
    2
  ]
}
